apiVersion: v1
kind: PersistentVolume
metadata:
  name: pillars-pv
  labels:
    name: pillars-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  csi:
    driver: fuse.csi.pillars.io
    volumeHandle: pillars-pv
    volumeAttributes:
      pillars_path: "/mnt/alluxio"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: test
          operator: In
          values:
          - abc