apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pillars-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
#  selector:
#    matchExpressions:
#    - key: name
#      operator: In
#      values: ["pillars-pv"]